FROM ghcr.io/postalserver/postal:latest

COPY app/lib/smtp_client/server.rb /opt/postal/app/app/lib/smtp_client/server.rb
COPY app/lib/smtp_client/endpoint.rb /opt/postal/app/app/lib/smtp_client/endpoint.rb
COPY app/senders/smtp_sender.rb /opt/postal/app/app/senders/smtp_sender.rb
